"""Import an extracted STEG Prosol dashboard into a normalized JSON snapshot.

The importer follows the report's rooftop-PV sections and deliberately excludes
section 6 (Chauffe-Eau-Solaire / CES). It is designed for the text generated by:

    pdftotext -layout report.pdf report.txt

Usage:
    python -m reports.prosol_report_importer \
        data/source/prosol_mars_2026_2.txt \
        --output reports/generated/prosol_mars_2026.json
"""

from __future__ import annotations

if __package__ in (None, ""):  # launched as `python <dir>/<file>.py`: add the project root
    import pathlib
    import sys
    sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import argparse
import csv
import json
import re
from collections.abc import Sequence
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from data.io import write_json_atomic
from data.paths import relative_to_project
from data.prosol_report_schema import SNAPSHOT_SCOPE


NUMBER = r"-?\d+(?:[.,]\d+)?"
NUMBER_RE = re.compile(NUMBER)
MONTHS = {
    "janvier": "01", "février": "02", "mars": "03", "avril": "04",
    "mai": "05", "juin": "06", "juillet": "07", "août": "08",
    "septembre": "09", "octobre": "10", "novembre": "11", "décembre": "12",
}
# Fallbacks when the layout of an exported PDF defeats the header regexes
DEFAULT_MONTH = "01"
UNKNOWN_PERIOD = "unknown"

# Official national totals printed by the report; the district tables must add
# up to them for the snapshot to be trusted (see ``EXPECTED`` below).
EXPECTED: dict[str, dict[str, Any]] = {
    "installations": {"current_month": 3211, "current_year_to_date": 9340, "since_program_start": 144979},
    "installed_power_mw": {"current_month": 11.8, "current_year_to_date": 33.8, "since_program_start": 456.0},
    "pending_dossiers": {"current_year_to_date": 3171, "since_2018": 5475},
}
# STEG publishes 50 districts; a shorter table means the parser missed rows
EXPECTED_DISTRICT_COUNT = 50
# The source report itself has a documented district-to-national reconciliation
# gap of up to 0.3 MW; do not hide or reject it.
POWER_GAP_TOLERANCE_MW = 0.3
POWER_GAP_DECIMALS = 2
# Row labels that are layout artefacts rather than data rows
IGNORED_ROW_LABELS = frozenset({"TOTAL"})

# Section anchors, quoted exactly as pdftotext renders the report headings
NATIONAL_TABLE_ANCHOR = "Nombre d’installations PV"
NATIONAL_TABLE_ROWS = 16
SECTION_DIRECTION_INSTALLATIONS = ("3.3. Nombre d'IPV par Direction", "3.4. Nombre des IPV par District")
SECTION_DISTRICT_INSTALLATIONS = ("3.4. Nombre des IPV par District", "4. Puissances Installées")
SECTION_DIRECTION_POWER = ("4.3. Puissances Installées par Direction", "4.4. Puissances Installées par District")
SECTION_DISTRICT_POWER = ("4.4. Puissances Installées par District", "5. Répartition des IPV")
SECTION_PENDING = ("7. Nombre de dossiers PV en instance", "Programme Prosol")
SECTION_SIZES = ("5.1. Nombre d'installation PV", "5.2. Puissances installées")

SNAPSHOT_NATIONAL_UNIT = "reported"
EXCLUDED_SECTIONS = ["6. Chauffe-Eau-Solaire (CES)"]
REGISTRY_FILENAME = "report_registry.json"
CSV_FILENAMES = {
    "national": "national_metrics.csv",
    "directions": "direction_metrics.csv",
    "districts": "district_metrics.csv",
    "sizes": "installation_sizes.csv",
    "pending": "pending_dossiers.csv",
}


def normalize_line(line: str) -> str:
    """Remove layout-only thousands spaces and normalize decimal commas."""
    # Remove only single thousands separators, not column spacing.
    line = re.sub(r"(?<=\d) (?=\d)", "", line)
    return line.replace("−", "-").strip()


def number(value: str) -> float:
    return float(value.replace(",", "."))


def numeric_tail(line: str, expected: int) -> tuple[str, list[float]] | None:
    """Return a row label and its final numeric columns."""
    normalized = normalize_line(line)
    matches = list(NUMBER_RE.finditer(normalized))
    if len(matches) < expected:
        return None

    selected = matches[-expected:]
    label = normalized[: selected[0].start()].strip()
    values = [number(match.group()) for match in selected]
    return label, values


def comparison(values: Sequence[float | None], unit: str) -> dict[str, Any]:
    """Map the report's five-period comparison columns."""
    if len(values) == 6:
        # The report leaves variance blank when the previous-year value is 0.
        values = [values[0], values[1], None, values[2], values[3], values[4], values[5]]
    if len(values) != 7:
        raise ValueError(f"Expected 7 comparison values, got {values}")
    return {
        "current_month": values[0],
        "previous_year_month": values[1],
        "variance_month_pct": values[2],
        "current_year_to_date": values[3],
        "previous_year_to_date": values[4],
        "variance_ytd_pct": values[5],
        "since_program_start": values[6],
        "unit": unit,
    }


def section(lines: list[str], start: str, end: str) -> list[str]:
    start_index = next(i for i, line in enumerate(lines) if start in line)
    end_index = next(
        (i for i in range(start_index + 1, len(lines)) if end in lines[i]),
        len(lines),
    )
    return lines[start_index + 1 : end_index]


def _is_data_row(label: str) -> bool:
    """False for blank, total or number-led labels produced by table layout."""
    return bool(label) and label.upper() not in IGNORED_ROW_LABELS and not label[0].isdigit()


def parse_comparison_rows(lines: list[str], unit: str) -> list[dict[str, Any]]:
    rows = []
    for line in lines:
        parsed = numeric_tail(line, 7) or numeric_tail(line, 6)
        if not parsed:
            continue
        label, values = parsed
        if not _is_data_row(label):
            continue
        rows.append({"name": label, **comparison(values, unit)})
    return rows


def parse_pending_rows(lines: list[str]) -> list[dict[str, Any]]:
    rows = []
    for line in lines:
        parsed = numeric_tail(line, 5)
        if not parsed:
            continue
        label, values = parsed
        if not _is_data_row(label):
            continue
        rows.append(
            {
                "district": label,
                "current_year_to_date": int(values[0]),
                "previous_year_to_date": int(values[1]),
                "variance_ytd_pct": values[2],
                "since_2018": int(values[3]),
                "share_pct": values[4],
            }
        )
    return rows


def parse_size_rows(lines: list[str]) -> list[dict[str, Any]]:
    rows = []
    for line in lines:
        parsed = numeric_tail(line, 7)
        if not parsed:
            continue
        label, values = parsed
        if not label or label.lower() == "total":
            continue
        size_match = re.search(r"(\d+)\s*kWc", label, re.IGNORECASE)
        if not size_match:
            continue
        rows.append(
            {
                "system_size_kwc": int(size_match.group(1)),
                **comparison(values, "installations"),
            }
        )
    unique_rows = {}
    for row in rows:
        unique_rows[row["system_size_kwc"]] = row
    return [unique_rows[size] for size in sorted(unique_rows)]


def export_csvs(snapshot: dict[str, Any], output_dir: Path) -> list[Path]:
    """Export the report sections as flat CSV files for analysis/import."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written = []

    def write_rows(filename: str, rows: list[dict[str, Any]]) -> None:
        if not rows:
            return
        path = output_dir / filename
        fieldnames = list(dict.fromkeys(key for row in rows for key in row))
        with path.open("w", encoding="utf-8", newline="") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
        written.append(path)

    write_rows(CSV_FILENAMES["national"], snapshot["national_rows"])

    power_by_direction = {row["name"]: row for row in snapshot["direction_power"]}
    directions = []
    for row in snapshot["directions"]:
        power = power_by_direction.get(row["name"], {})
        directions.append({
            **row,
            "power_current_month": power.get("current_month"),
            "power_previous_year_month": power.get("previous_year_month"),
            "power_current_year_to_date": power.get("current_year_to_date"),
            "power_previous_year_to_date": power.get("previous_year_to_date"),
            "power_since_program_start": power.get("since_program_start"),
        })
    write_rows(CSV_FILENAMES["directions"], directions)

    districts = []
    for row in snapshot["districts"]:
        flat = {key: value for key, value in row.items() if key not in ("installed_power", "pending_dossiers")}
        flat.update({f"power_{key}": value for key, value in row.get("installed_power", {}).items() if key != "name"})
        flat.update({f"pending_{key}": value for key, value in (row.get("pending_dossiers") or {}).items() if key != "district"})
        districts.append(flat)
    write_rows(CSV_FILENAMES["districts"], districts)
    write_rows(CSV_FILENAMES["sizes"], snapshot["installation_sizes"])
    write_rows(CSV_FILENAMES["pending"], snapshot["pending_dossiers"])
    return written


def parse_report(source: Path) -> dict[str, Any]:
    lines = source.read_text(encoding="utf-8").splitlines()
    text = "\n".join(lines)

    emission_match = re.search(r"Date d'émission\s*:\s*(\d{2}/\d{2}/\d{4})", text)
    emission_date = emission_match.group(1) if emission_match else None
    period_match = re.search(r"(?:Etat|Mars|Janvier|Février|Avril|Mai|Juin|Juillet|Août|Septembre|Octobre|Novembre|Décembre)\s*:?\s*(\w+)\s+(20\d{2})", text, re.IGNORECASE)
    if period_match:
        month_name, year = period_match.groups()
        report_period = f"{year}-{MONTHS.get(month_name.lower(), DEFAULT_MONTH)}"
    else:
        report_period = UNKNOWN_PERIOD

    national_rows = []
    national_start = next(i for i, line in enumerate(lines) if NATIONAL_TABLE_ANCHOR in line)
    for line in lines[national_start : national_start + NATIONAL_TABLE_ROWS]:
        parsed = numeric_tail(line, 7) or numeric_tail(line, 6)
        if parsed:
            label, values = parsed
            if label and not label[0].isdigit():
                national_rows.append({"name": label, **comparison(values, SNAPSHOT_NATIONAL_UNIT)})

    direction_installations = parse_comparison_rows(section(lines, *SECTION_DIRECTION_INSTALLATIONS), "installations")
    district_installations = parse_comparison_rows(section(lines, *SECTION_DISTRICT_INSTALLATIONS), "installations")
    direction_power = parse_comparison_rows(section(lines, *SECTION_DIRECTION_POWER), "MW")
    district_power = parse_comparison_rows(section(lines, *SECTION_DISTRICT_POWER), "MW")
    pending = parse_pending_rows(section(lines, *SECTION_PENDING))
    installation_sizes = parse_size_rows(section(lines, *SECTION_SIZES))

    power_by_district = {row["name"]: row for row in district_power}
    districts = []
    for row in district_installations:
        power = power_by_district.get(row["name"], {})
        districts.append({
            **row,
            "installed_power": power,
            "pending_dossiers": next(
                (item for item in pending if item["district"] == row["name"]),
                None,
            ),
        })

    district_installation_totals = {
        "current_month": sum(row["current_month"] for row in district_installations),
        "current_year_to_date": sum(row["current_year_to_date"] for row in district_installations),
        "since_program_start": sum(row["since_program_start"] for row in district_installations),
    }
    district_power_totals = {
        "current_month": sum(row["current_month"] for row in district_power),
        "current_year_to_date": sum(row["current_year_to_date"] for row in district_power),
        "since_program_start": sum(row["since_program_start"] for row in district_power),
    }
    pending_totals = {
        "current_year_to_date": sum(row["current_year_to_date"] for row in pending),
        "since_2018": sum(row["since_2018"] for row in pending),
    }
    # Copied so that consumers editing the snapshot cannot mutate the module
    expected = {name: dict(values) for name, values in EXPECTED.items()}
    power_gaps = {
        key: round(expected["installed_power_mw"][key] - district_power_totals[key], POWER_GAP_DECIMALS)
        for key in expected["installed_power_mw"]
    }
    district_names = [row["name"] for row in district_installations]
    pending_names = [row["district"] for row in pending]
    duplicate_districts = sorted({name for name in district_names if district_names.count(name) > 1})
    missing_pending_rows = sorted(set(district_names) - set(pending_names))
    within_power_tolerance = all(abs(gap) <= POWER_GAP_TOLERANCE_MW for gap in power_gaps.values())
    reconciliation = {
        "district_count": len(district_names),
        "pending_dossier_count": len(pending_names),
        "duplicate_districts": duplicate_districts,
        "missing_pending_rows": missing_pending_rows,
        "installations": district_installation_totals,
        "installed_power_mw": district_power_totals,
        "pending_dossiers": pending_totals,
        "expected": expected,
        "district_power_gap_mw": power_gaps,
        # The source report has a documented district-to-national gap; keep it
        # visible instead of silently rejecting the snapshot.
        "power_gap_within_report_tolerance": within_power_tolerance,
        "passed": (
            len(district_names) == EXPECTED_DISTRICT_COUNT
            and len(pending_names) == EXPECTED_DISTRICT_COUNT
            and not duplicate_districts
            and not missing_pending_rows
            and district_installation_totals == expected["installations"]
            and within_power_tolerance
            and pending_totals == expected["pending_dossiers"]
        ),
    }

    return {
        "scope": SNAPSHOT_SCOPE,
        "report_period": report_period,
        "emission_date": emission_date,
        "source_file": source.name,
        "reconciliation": reconciliation,
        "national_rows": national_rows,
        "directions": direction_installations,
        "direction_power": direction_power,
        "districts": districts,
        "installation_sizes": installation_sizes,
        "pending_dossiers": pending,
        "excluded_sections": list(EXCLUDED_SECTIONS),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--registry", type=Path, default=None)
    parser.add_argument("--csv-dir", type=Path, default=None)
    args = parser.parse_args()

    snapshot = parse_report(args.source)
    if not snapshot["reconciliation"]["passed"]:
        raise SystemExit("Prosol report reconciliation failed: district totals do not match the official national totals.")
    write_json_atomic(args.output, snapshot)

    registry_path = args.registry or args.output.parent / REGISTRY_FILENAME
    # Strict read: a corrupt registry must not be silently replaced by a new one
    registry = json.loads(registry_path.read_text(encoding="utf-8")) if registry_path.exists() else []
    entry = {
        "report_period": snapshot["report_period"],
        "emission_date": snapshot["emission_date"],
        "source_file": snapshot["source_file"],
        "snapshot_file": relative_to_project(args.output),
        "scope": snapshot["scope"],
        "reconciliation_passed": snapshot["reconciliation"]["passed"],
        "imported_at": datetime.now(timezone.utc).isoformat(),
    }
    registry = [item for item in registry if item.get("source_file") != entry["source_file"]]
    registry.append(entry)
    write_json_atomic(registry_path, registry)

    if args.csv_dir:
        csv_files = export_csvs(snapshot, args.csv_dir)
        print(f"CSV files exported: {len(csv_files)}")

    print(f"Imported {snapshot['source_file']} -> {args.output}")
    print(f"District rows: {len(snapshot['districts'])}")
    print(f"Pending rows: {len(snapshot['pending_dossiers'])}")
    print(f"Installation-size rows: {len(snapshot['installation_sizes'])}")


if __name__ == "__main__":
    main()
